#!/bin/bash
# ══════════════════════════════════════════════════════════════
# update-readme.sh — Dynamic Profile README Section Updater
# Project 1: Generates README sections dynamically
# Usage: ./update-readme.sh <section> <last_updated> <theme>
# ══════════════════════════════════════════════════════════════

SECTION="${1:-header}"
LAST_UPDATED="${2:-$(date '+%Y-%m-%d %H:%M UTC')}"
THEME="${3:-dark}"

echo "📝 Updating README section: $SECTION (theme=$THEME)"

case "$SECTION" in
  header)
    cat > /tmp/readme_header.md << HEREDOC
<!-- README auto-generated by GitHub Actions 🤖 -->
<!-- Last updated: $LAST_UPDATED -->

# 👋 Hi, I'm $GITHUB_ACTOR!

> 🤖 *This README is automatically updated daily by a GitHub Actions workflow.*
> *Theme: **$THEME** | Last updated: **$LAST_UPDATED***

---
HEREDOC
    echo "✅ Header section written."
    ;;

  stats)
    cat > /tmp/readme_stats.md << HEREDOC

## 📊 GitHub Stats

![GitHub Stats](https://github-readme-stats.vercel.app/api?username=$GITHUB_ACTOR&show_icons=true&theme=$THEME)

![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=$GITHUB_ACTOR&layout=compact&theme=$THEME)

---
HEREDOC
    echo "✅ Stats section written."
    ;;

  footer)
    cat > /tmp/readme_footer.md << HEREDOC

## 🚀 Powered By

| Tool | Purpose |
|------|---------|
| GitHub Actions | Automation & CI/CD |
| GH-200 CoHack | Workshop & Learning |
| figlet | ASCII Art Banners |

---
*🤖 Automatically updated by [GitHub Actions](https://github.com/features/actions)*
HEREDOC
    echo "✅ Footer section written."
    ;;

  *)
    echo "⚠️ Unknown section: $SECTION. Use: header, stats, or footer."
    exit 1
    ;;
esac

# Combine all sections into README.md
cat /tmp/readme_header.md /tmp/readme_stats.md /tmp/readme_footer.md > README.md 2>/dev/null || echo "Note: Some sections not yet generated"
echo "📄 README.md updated for section: $SECTION"
